#!/usr/bin/env node
/*
 * Builds the Cloudflare offline worker from offline.html.
 *
 * The page it serves has to render with the Pi unreachable - that is the
 * entire failure case - so every asset is inlined as a data: URI here
 * rather than fetched. The sources are the live frontend files, not
 * copies, so a re-bake of the press tile or a new nest illustration is
 * picked up by re-running this script.
 *
 * Emits:
 *   worker.js    the deployable module worker (HTML frozen inside it)
 *   preview.html byte-identical page content, openable from disk
 *
 * Both are generated. Edit offline.html, never these.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const HERE     = __dirname;
const FRONTEND = path.resolve(HERE, '../../frontend');
const ASSETS   = path.resolve(HERE, '../../assets');

const ASSET_MAP = {
  '{{BENCH_WEBP}}':  { file: path.join(HERE,     'bench-cliff.webp'), mime: 'image/webp' },
  '{{PRESS_PNG}}':   { file: path.join(FRONTEND, 'stats-press.png'), mime: 'image/png'  },
  '{{FAVICON_PNG}}': { file: path.join(ASSETS,   'favicon.png'),     mime: 'image/png'  },
  // Read from the live frontend rather than hand-copied, so the mark here
  // can never drift from the one on the collage.
  '{{MARK_SVG}}':    { file: path.join(FRONTEND, '7ml-mark.svg'),    mime: 'image/svg+xml' },
};

function dataUri({ file, mime }) {
  return `data:${mime};base64,${fs.readFileSync(file).toString('base64')}`;
}

function build() {
  const src = path.join(HERE, 'offline.html');
  let html = fs.readFileSync(src, 'utf8');

  for (const [token, asset] of Object.entries(ASSET_MAP)) {
    if (!html.includes(token)) throw new Error(`offline.html no longer uses ${token}`);
    html = html.split(token).join(dataUri(asset));
  }

  // A surviving {{...}} means a token was added to the page but never
  // registered above, and would ship to visitors as literal braces.
  const stray = html.match(/\{\{[A-Z0-9_]+\}\}/g);
  if (stray) throw new Error(`unresolved placeholder(s): ${[...new Set(stray)].join(', ')}`);

  // The HTML goes into the worker as a template literal, so the three
  // sequences that can end or escape one have to be neutralised.
  const embedded = html
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  const worker = `/*
 * GENERATED by build.js - do not edit.
 * Source: offline.html   Rebuild: node build.js
 *
 * Sits on the birds.7ml.in root route. Passes a healthy station through
 * untouched; serves the self-contained offline page when the tunnel is
 * down, so visitors get the collage's own empty-nest voice instead of
 * Cloudflare's error 1033 interstitial.
 */
'use strict';

const OFFLINE_HTML = \`${embedded}\`;

/* Statuses that mean "the station did not answer", not "the station said
 * no". 502/503/504 are the tunnel or Caddy failing; 520-527 are
 * Cloudflare's own origin-unreachable family; 530 carries error 1033,
 * the tunnel being disconnected entirely. A 4xx is a real answer from a
 * live station and must pass through. */
const ORIGIN_DOWN = new Set([502, 503, 504, 520, 521, 522, 523, 524, 525, 526, 527, 530]);

/* Cloudflare would wait ~100s on a hung tunnel. A visitor should not. */
const ORIGIN_TIMEOUT_MS = 10000;

function offlineResponse() {
  return new Response(OFFLINE_HTML, {
    /* 503 keeps this out of search indexes and out of any cache that
     * honours status, so an outage snapshot can never stand in for the
     * real collage once the station is back. */
    status: 503,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store, must-revalidate',
      'retry-after': '30',
      'x-robots-tag': 'noindex, nofollow',
      /* The page's own recovery poll reads this: its absence on a 200 is
       * what tells the tab the station is answering again. */
      'x-avian-offline': '1',
    },
  });
}

export default {
  async fetch(request) {
    let response;
    try {
      response = await fetch(request, { signal: AbortSignal.timeout(ORIGIN_TIMEOUT_MS) });
    } catch (err) {
      /* Thrown rather than returned: DNS/connect failure, or our timeout. */
      return offlineResponse();
    }

    if (ORIGIN_DOWN.has(response.status)) return offlineResponse();
    return response;
  },
};
`;

  fs.writeFileSync(path.join(HERE, 'worker.js'), worker);
  fs.writeFileSync(path.join(HERE, 'preview.html'), html);

  const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
  console.log(`preview.html  ${kb(Buffer.byteLength(html))}`);
  console.log(`worker.js     ${kb(Buffer.byteLength(worker))}`);
}

build();
